//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khabirova41Size
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductCost { get; set; }
        public Nullable<byte> ProductDiscountAmount { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductProvider { get; set; }
        public string ProductCategory { get; set; }
        public Nullable<int> ProductDiscount { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string ProductPhoto { get; set; }
        public string ProductStatus { get; set; }
    
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public int Quantity { get; set; }

        public int inStock
        {
            get
            {

                int stock = (int)(ProductQuantityInStock - Quantity);
                if (stock < 0)
                {
                    return 0;
                }
                else
                {
                    return stock;
                }
            }
        }
    }
}
